package com.wts.entity.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDepartment<M extends BaseDepartment<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setSzcs(java.lang.String szcs) {
		set("szcs", szcs);
	}
	
	public java.lang.String getSzcs() {
		return getStr("szcs");
	}

	public void setDwzd(java.lang.String dwzd) {
		set("dwzd", dwzd);
	}
	
	public java.lang.String getDwzd() {
		return getStr("dwzd");
	}

	public void setDwlb(java.lang.String dwlb) {
		set("dwlb", dwlb);
	}
	
	public java.lang.String getDwlb() {
		return getStr("dwlb");
	}

	public void setDwlx(java.lang.String dwlx) {
		set("dwlx", dwlx);
	}
	
	public java.lang.String getDwlx() {
		return getStr("dwlx");
	}

	public void setSjdw(java.lang.String sjdw) {
		set("sjdw", sjdw);
	}
	
	public java.lang.String getSjdw() {
		return getStr("sjdw");
	}

	public void setDwbh(java.lang.String dwbh) {
		set("dwbh", dwbh);
	}
	
	public java.lang.String getDwbh() {
		return getStr("dwbh");
	}

	public void setDwmc(java.lang.String dwmc) {
		set("dwmc", dwmc);
	}
	
	public java.lang.String getDwmc() {
		return getStr("dwmc");
	}

	public void setQtmc(java.lang.String qtmc) {
		set("qtmc", qtmc);
	}
	
	public java.lang.String getQtmc() {
		return getStr("qtmc");
	}

	public void setLdzs(java.lang.String ldzs) {
		set("ldzs", ldzs);
	}
	
	public java.lang.String getLdzs() {
		return getStr("ldzs");
	}

	public void setJb(java.lang.String jb) {
		set("jb", jb);
	}
	
	public java.lang.String getJb() {
		return getStr("jb");
	}

	public void setNsjg(java.lang.String nsjg) {
		set("nsjg", nsjg);
	}
	
	public java.lang.String getNsjg() {
		return getStr("nsjg");
	}

	public void setZyzz(java.lang.String zyzz) {
		set("zyzz", zyzz);
	}
	
	public java.lang.String getZyzz() {
		return getStr("zyzz");
	}

	public void setXzPlanNum(java.lang.String xzPlanNum) {
		set("xz_plan_num", xzPlanNum);
	}
	
	public java.lang.String getXzPlanNum() {
		return getStr("xz_plan_num");
	}

	public void setXzRealNum(java.lang.String xzRealNum) {
		set("xz_real_num", xzRealNum);
	}
	
	public java.lang.String getXzRealNum() {
		return getStr("xz_real_num");
	}

	public void setXzLoneNum(java.lang.String xzLoneNum) {
		set("xz_lone_num", xzLoneNum);
	}
	
	public java.lang.String getXzLoneNum() {
		return getStr("xz_lone_num");
	}

	public void setSyPlanNum(java.lang.String syPlanNum) {
		set("sy_plan_num", syPlanNum);
	}
	
	public java.lang.String getSyPlanNum() {
		return getStr("sy_plan_num");
	}

	public void setSyRealNum(java.lang.String syRealNum) {
		set("sy_real_num", syRealNum);
	}
	
	public java.lang.String getSyRealNum() {
		return getStr("sy_real_num");
	}

	public void setSyLoneNum(java.lang.String syLoneNum) {
		set("sy_lone_num", syLoneNum);
	}
	
	public java.lang.String getSyLoneNum() {
		return getStr("sy_lone_num");
	}

	public void setGqPlanNum(java.lang.String gqPlanNum) {
		set("gq_plan_num", gqPlanNum);
	}
	
	public java.lang.String getGqPlanNum() {
		return getStr("gq_plan_num");
	}

	public void setGqRealNum(java.lang.String gqRealNum) {
		set("gq_real_num", gqRealNum);
	}
	
	public java.lang.String getGqRealNum() {
		return getStr("gq_real_num");
	}

	public void setGqLoneNum(java.lang.String gqLoneNum) {
		set("gq_lone_num", gqLoneNum);
	}
	
	public java.lang.String getGqLoneNum() {
		return getStr("gq_lone_num");
	}

	public void setUrl(java.lang.String url) {
		set("url", url);
	}
	
	public java.lang.String getUrl() {
		return getStr("url");
	}

	public void setTime(java.lang.String time) {
		set("time", time);
	}
	
	public java.lang.String getTime() {
		return getStr("time");
	}

}
