package com.wts.entity.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDepartmentErr<M extends BaseDepartmentErr<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setDwbh(java.lang.String dwbh) {
		set("dwbh", dwbh);
	}
	
	public java.lang.String getDwbh() {
		return getStr("dwbh");
	}

	public void setDwmc(java.lang.String dwmc) {
		set("dwmc", dwmc);
	}
	
	public java.lang.String getDwmc() {
		return getStr("dwmc");
	}

	public void setUrl(java.lang.String url) {
		set("url", url);
	}
	
	public java.lang.String getUrl() {
		return getStr("url");
	}

}
