package com.wts.entity.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseJsonstr<M extends BaseJsonstr<M>> extends Model<M> implements IBean {

	public void setI(java.lang.Integer i) {
		set("i", i);
	}
	
	public java.lang.Integer getI() {
		return getInt("i");
	}

	public void setId(java.lang.String id) {
		set("id", id);
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}

	public void setPid(java.lang.String pid) {
		set("pid", pid);
	}
	
	public java.lang.String getPid() {
		return getStr("pid");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}

	public void setDwbh(java.lang.String dwbh) {
		set("dwbh", dwbh);
	}
	
	public java.lang.String getDwbh() {
		return getStr("dwbh");
	}

}
