package com.wts.entity.model;

import com.wts.entity.base.BaseAdvice;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Advice extends BaseAdvice<Advice> {
	public static final Advice dao = new Advice().dao();
}
