package com.wts.entity.model;

import com.wts.entity.base.BaseDepartmentErr;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DepartmentErr extends BaseDepartmentErr<DepartmentErr> {
	public static final DepartmentErr dao = new DepartmentErr().dao();
}
