package com.wts.entity.model;

import com.wts.entity.base.BaseJsonstr;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Jsonstr extends BaseJsonstr<Jsonstr> {
	public static final Jsonstr dao = new Jsonstr().dao();
}
