package com.wts.entity.model;

import com.wts.entity.base.BaseJson;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Json extends BaseJson<Json> {
	public static final Json dao = new Json().dao();
}
