package com.wts.entity.model;

import com.wts.entity.base.BasePersonErr;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PersonErr extends BasePersonErr<PersonErr> {
	public static final PersonErr dao = new PersonErr().dao();
}
